# -*- coding: utf-8 -*-
"""Cópia de Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lRNe31dWperhypjhoB7_3pIy8_HH3bmv
"""

!pip install basedosdados
import basedosdados as bd
import pandas as pd

#busca de dados de abandono do ensino medio
query = """
SELECT
    ano,
    id_municipio,
    rede,
    taxa_abandono_em,
    taxa_abandono_em_1_ano,
    taxa_abandono_em_2_ano,
    taxa_abandono_em_3_ano
FROM `basedosdados.br_inep_indicadores_educacionais.municipio`
WHERE ano = 2022
"""

print("Buscando dados...")

df_educacao = bd.read_sql(query, billing_project_id="projeto-escola-dados")

#limpeza de dados
df_clean = df_educacao.dropna(subset=['taxa_abandono_em']).copy()

#mapeando muninipios a partir do id
codigos_uf = {
    '11': 'RO', '12': 'AC', '13': 'AM', '14': 'RR', '15': 'PA', '16': 'AP', '17': 'TO',
    '21': 'MA', '22': 'PI', '23': 'CE', '24': 'RN', '25': 'PB', '26': 'PE', '27': 'AL', '28': 'SE', '29': 'BA',
    '31': 'MG', '32': 'ES', '33': 'RJ', '34': 'SP', '35': 'SP',
    '41': 'PR', '42': 'SC', '43': 'RS',
    '50': 'MS', '51': 'MT', '52': 'GO', '53': 'DF'
}
df_clean['sigla_uf'] = df_clean['id_municipio'].astype(str).str[:2].map(codigos_uf)

print("Dados limpos e estruturados!")
print(df_clean.head())

# Ver a média nacional de abandono no Ensino Médio Público
print("--- Média Nacional de Abandono (Ensino Médio Público) ---")
print(df_clean['taxa_abandono_em'].describe())

# Comparação por ano (Onde o aluno desiste mais)
print("\n--- Média de Abandono por Ano Escolar ---")
print(f"1º Ano: {df_clean['taxa_abandono_em_1_ano'].mean():.2f}%")
print(f"2º Ano: {df_clean['taxa_abandono_em_2_ano'].mean():.2f}%")
print(f"3º Ano: {df_clean['taxa_abandono_em_3_ano'].mean():.2f}%")

# Ranking dos 5 Estados com maior abandono médio
print("\n--- Top 5 Estados com Maior Abandono Escolar ---")
ranking_uf = df_clean.groupby('sigla_uf')['taxa_abandono_em'].mean().sort_values(ascending=False)
print(ranking_uf.head(5))
# Exportando o DataFrame diretamente para o formato Excel (.xlsx)(tive problema com o ultimo codigo com isso)
nome_do_arquivo = "meus_dados_evasao_escolar.xlsx"

# O parâmetro index=False
df_clean.to_excel(nome_do_arquivo, index=False)
print(f"Pronto!")